# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "github-actions" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Show all downloaded files
      run: |
        ls
    - name: Uninstall core packages
      run: |
        pip uninstall Flask Flask-JWT-Extended Flask-RESTful Flask-SQLAlchemy PyJWT pytest pylint -y
    - name: Cleanup previous job Docker images
      run: |
        docker rmi adrianpanek/python-app:latest
    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

